// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Q0yEpu-vFxC3CtlTSs4PmPSd3Fx1ues',
    appId: '1:181946388516:web:aeeea61e4e6ee5080d08b1',
    messagingSenderId: '181946388516',
    projectId: 'jurnaljatimcarnival',
    authDomain: 'jurnaljatimcarnival.firebaseapp.com',
    storageBucket: 'jurnaljatimcarnival.firebasestorage.app',
    measurementId: 'G-5E7GPN4W9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlmEFqnwWShHEjdCQcR6GkkahAFG0tM_w',
    appId: '1:181946388516:android:856850490e770a220d08b1',
    messagingSenderId: '181946388516',
    projectId: 'jurnaljatimcarnival',
    storageBucket: 'jurnaljatimcarnival.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHZfk9IVViFbdrya7jrIXP40prBIFVKY',
    appId: '1:181946388516:ios:3041877446e071da0d08b1',
    messagingSenderId: '181946388516',
    projectId: 'jurnaljatimcarnival',
    storageBucket: 'jurnaljatimcarnival.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHZfk9IVViFbdrya7jrIXP40prBIFVKY',
    appId: '1:181946388516:ios:3041877446e071da0d08b1',
    messagingSenderId: '181946388516',
    projectId: 'jurnaljatimcarnival',
    storageBucket: 'jurnaljatimcarnival.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Q0yEpu-vFxC3CtlTSs4PmPSd3Fx1ues',
    appId: '1:181946388516:web:2ff7f67a3700cda20d08b1',
    messagingSenderId: '181946388516',
    projectId: 'jurnaljatimcarnival',
    authDomain: 'jurnaljatimcarnival.firebaseapp.com',
    storageBucket: 'jurnaljatimcarnival.firebasestorage.app',
    measurementId: 'G-DQLG7XBCKN',
  );
}
